### ISSUE TITLE
Run trial on GCP with new SA

### ISSUE THREAD

**Issue by rawanmahdi** [DSC-McMaster-U/Auto-ML#129]

**Comment by ausbennett** [comment]
![image](https://github.com/DSC-McMaster-U/Auto-ML/assets/61357467/471b1931-1d1c-4132-a301-6f609f23e40d)

**I think out current manual_terraform.yml is ok**

It looks like the flow is failing due to our project being config'd to require 600gb of SSD space? I'm not sure where but it defintely seems like a GCP config issue.

**Comment by rawanmahdi** [comment]
@ausbennett have you read through this: https://stackoverflow.com/questions/74836213/error-403-insufficient-regional-quota-to-satisfy-request-resource-ssd-total
I don't know how our project would be configured to a certain requirement, dont think that came up when I declared it but the thing this stackoverflow thread is saying about setting the location to a zone rather than a region in the `"google_container_cluster"` and the `"google_container_node_pool"` blocks. I'll try it and lyk.
