### ISSUE TITLE
Setup Automated API testing!!!

### ISSUE THREAD

**Issue by rawanmahdi** [DSC-McMaster-U/Auto-ML#181]
Ideas:
 - Taking the github actions approach, and using the fastapi testing client to generate tests, then call them through pytest and a github workflow that runs after every PR for the backend folder. See [this](https://github.com/alehpineda/fastapi_test/tree/master) example.
 - Or a way cooler idea: setup a jenkins pipeline! this will be harder/kind of overkill but a good new framework to pick up!

(if we need more tickets we'll do both for fun :) )

**Comment by habibur4340** [comment]
Hey @rawanmahdi 
Setting up automated API testing? You're in luck because [Apidog](https://apidog.com/) is just the tool for the job. It's tailor-made for creating automated test scenarios for your APIs. With Apidog, you can easily automate repetitive test cases, saving you a boatload of time and effort. It’s user-friendly, so you won’t be scratching your head over complex configurations. Just set it up, and let Apidog handle the grunt work of testing your APIs regularly. For hassle-free and efficient automated API testing, Apidog is a top pick!
